version: "3"

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_NAME: Pawsome
      APP_ENV: local
      APP_KEY: base64:x8R6dkYsT0Ceoibyg0LgS9C9n5lbjr1mqjyZOpK6/VI=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pawsome_laravel
      DB_USERNAME: pawsome_user
      DB_PASSWORD: pawsome_password
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: pawsome_laravel
      MYSQL_USER: pawsome_user
      MYSQL_PASSWORD: pawsome_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
