[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18']

[phases.install]
cmds = [
    'nix-env -iA nixpkgs.php82Extensions.mongodb',
    'composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-mongodb'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'