[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.mongodb', 'nodejs_18']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'