[[buildpacks]]
id = "paketo-buildpacks/php"
version = "latest"

[build]
  [[build.env]]
  name = "BP_PHP_VERSION"
  value = "8.2.*"
  
  [[build.env]]
  name = "BP_PHP_SERVER"
  value = "php-server"
  
  [[build.env]]
  name = "BP_PHP_COMPOSER_VERSION"
  value = "2.6.*"
  
  [[build.env]]
  name = "BP_PHP_COMPOSER_INSTALL_OPTIONS"
  value = "--no-dev --optimize-autoloader"

  [[build.env]]
  name = "BP_PHP_WEB_DIR"
  value = "public"