replicaCount: 1

image:
  repository: pawsome-laravel
  pullPolicy: IfNotPresent
  tag: "v5"

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

laravel:
  appName: "Pawsome"
  appEnv: "local"
  appDebug: true
  appUrl: "http://pawsome.local"
  appKey: "base64:x8R6dkYsT0Ceoibyg0LgS9C9n5lbjr1mqjyZOpK6/VI="

mysql:
  enabled: true
  auth:
    rootPassword: "pawsome-root-password"
    database: "pawsome_laravel"
    username: "pawsome_user"
    password: "pawsome_password"
  primary:
    persistence:
      enabled: true
      size: 1Gi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
